# Generated by Django 3.1.5 on 2021-01-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
