# Generated by Django 3.1.5 on 2021-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.CharField(default=3455, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_text',
            field=models.TextField(),
        ),
    ]
